# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-14 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import inventory_details.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvertoryStack',
            fields=[
                ('id', models.CharField(default=inventory_details.models.generate_unique, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_details.InvertoryStack')),
            ],
        ),
    ]
